L"function totalLeftOffset(element)"
L"{"
L"	var amount = 0;"
L"	while (element != null)"
L"	{"
L"		amount += element.offsetLeft;"
L"		element = element.offsetParent;"
L"	}"
L"	return amount;"
L"}"
L""
L"function totalTopOffset(element)"
L"{"
L"	var amount = 0;"
L"	while (element != null)"
L"	{"
L"		amount += element.offsetTop;"
L"		element = element.offsetParent;"
L"	}"
L"	return amount;"
L"}"
L""
L"function fixPageXY(e)"
L"{"
L"	if (e.pageX == null && e.clientX != null )"
L"	{"
L"		var html = document.documentElement;"
L"		var body = document.body;"
L"		e.pageX = e.clientX + (html.scrollLeft || body && body.scrollLeft || 0);"
L"		e.pageX -= html.clientLeft || 0;"
L"		e.pageY = e.clientY + (html.scrollTop || body && body.scrollTop || 0);"
L"		e.pageY -= html.clientTop || 0;"
L"	}"
L"}"
L""
L"function setSelection(elem, lastterm, curTerm)"
L"{"
L"	elem.id = 'lwtcursel';"
L"	lastterm.setAttribute('lwtcursel', curTerm);"
L"	elem.className = elem.className + ' lwtSel';"
L"}"
L""
L"function removeSelection()"
L"{"
L"	var elem = document.getElementById('lwtcursel');"
L"	if (elem == null)"
L"	{"
L"		return;"
L"	}"
L"	elem.id = '';"
L"	document.getElementById('lwtlasthovered').setAttribute('lwtcursel','');"
L"	var curClass = elem.className;"
L"	var lastSpace = curClass.lastIndexOf(' ');"
L"	if (lastSpace >= 0)"
L"	{"
L"		var putClass = curClass.substr(0, lastSpace + 1);"
L"		elem.className = putClass;"
L"	}"
L"}"
L""
L"function XOnElement(x, elem)"
L"{"
L"	if (x < totalLeftOffset(elem) || x >= totalLeftOffset(elem) + elem.offsetWidth)"
L"	{"
L"		return false;"
L"	}"
L"	return true;"
L"}"
L""
L"function YOnElement(y, elem)"
L"{"
L"	if (y < totalTopOffset(elem) || y >= totalTopOffset(elem) + elem.offsetHeight)"
L"	{"
L"		return false;"
L"	}"
L"	return true;"
L"}"
L""
L"function XYOnElement(x, y, elem)"
L"{"
L"	return (XOnElement(x, elem) && YOnElement(y, elem));"
L"}"
L""
L"function lwtcontextexit()"
L"{"
L"	removeSelection();"
L"	CloseOpenDialogs();"
L"}"
L""
L"function lwtdivmout(e)"
L"{"
L"	fixPageXY(e);"
L"	var statbox = document.getElementById('lwtinlinestat');"
L"	var bVal = XYOnElement(e.pageX, e.pageY, statbox);"
L"	if (bVal == false)"
L"	{"
L"		lwtmout(e);"
L"	}"
L"}"
L""
L"function lwtmout(e)"
L"{"
L"	fixPageXY(e);"
L"	var statbox = document.getElementById('lwtinlinestat');"
L"	if (!XYOnElement(e.pageX, e.pageY, statbox))"
L"	{"
L"		lwtcontextexit();"
L"	}"
L"}"
L""
L"function CloseOpenDialogs()"
L"{"
L"	document.getElementById('lwtinlinestat').style.display = 'none';"
L"}"
L""
L"function lwtkeypress()"
L"{"
L"	if (document.getElementById('lwtlasthovered').getAttribute('lwtcursel') == '')"
L"	{"
L"		return;"
L"	}"
L"	var e = window.event;"
L"	if (e.ctrlKey || e.altKey || e.shiftKey || e.metaKey)"
L"	{"
L"		return;"
L"		alert('in lwtkeypress return!');"
L"	}"
L"	switch(e.keyCode)"
L"	{"
L"		case 49:"
L"			document.getElementById('lwtsetstat1').click();"
L"			break;"
L"		case 50:"
L"			document.getElementById('lwtsetstat2').click();"
L"			break;"
L"		case 51:"
L"			document.getElementById('lwtsetstat3').click();"
L"			break;"
L"		case 52:"
L"			document.getElementById('lwtsetstat4').click();"
L"			break;"
L"		case 53:"
L"			document.getElementById('lwtsetstat5').click();"
L"			break;"
L"		case 87:"
L"			document.getElementById('lwtsetstat99').click();"
L"			break;"
L"		case 73:"
L"			document.getElementById('lwtsetstat98').click();"
L"			break;"
L"		case 85:"
L"			document.getElementById('lwtsetstat0').click();"
L"			break;"
L"		case 27:"
L"			CloseOpenDialogs();"
L"			break;"
L"	}"
L"}"
L""
L"function ExtrapLink(elem, linkForm, curTerm)"
L"{"
L"	if (elem == null) {return;}"
L"	var extrap = 'javascript:void(0);';"
L"	if (linkForm.indexOf('*') == 0)"
L"	{"
L"		extrap = linkForm.substr(1, linkForm.length);"
L"		extrap = extrap.replace('###', curTerm);"
L"		elem.setAttribute('target', '_blank');"
L"	}"
L"	else if (linkForm.indexOf('###') >= 0)"
L"	{"
L"		extrap = linkForm.replace('###', curTerm);"
L"		elem.setAttribute('target', '_blank');"
L"	}"
L"	elem.setAttribute('href', extrap);"
L"}"
L""
L"function lwtmover(whichid, e, origin)"
L"{"
L"/**/		//	alert('entering lwtmover');"
L"	removeSelection();"
L"	var divRec = document.getElementById(whichid);"
L"	var curTerm = divRec.getAttribute('lwtterm');"
L"	if (divRec == null) {alert('could not locate divRec');}"
L"	var lastterm = document.getElementById('lwtlasthovered');"
L"	if (lastterm == null) {alert('could not loccated lasthovered field');}"
L"	lastterm.setAttribute('lwtterm', curTerm);"
L"	lastterm.setAttribute('lwtstat', divRec.getAttribute('lwtstat'));"
L"	setSelection(origin, lastterm, curTerm);"
L"	document.attachEvent('onkeydown', lwtkeypress); "
L"	fixPageXY(e);"
L"	lwtshowinlinestat(e, curTerm);"
L"	var infobox = document.getElementById('lwtinfobox');"
L"	if (infobox == null) {alert('could not locate infobox to render popup');}"
L"	infobox.style.left = (e.pageX + 10) + 'px';"
L"	infobox.style.top = e.pageY + 'px';"
L"	document.getElementById('lwtinfoboxterm').innerText = curTerm;"
L"	document.getElementById('lwtinfoboxtrans').innerText = divRec.getAttribute('lwttrans');"
L"	document.getElementById('lwtinfoboxrom').innerText = divRec.getAttribute('lwtrom');"
L"/**/		//	infobox.style.display = 'block';"
L"}"
L""
L"function lwtshowinlinestat(e, curTerm)"
L"{"
L"	var statbox = document.getElementById('lwtinlinestat');"
L"	if (statbox == null)"
L"	{"
L"		alert('could not locate inline status change popup');"
L"		return;"
L"	}"
L"	statbox.style.left = totalLeftOffset(e.srcElement) + 'px';"
L"	var inlineTop = (totalTopOffset(e.srcElement) + e.srcElement.offsetHeight);"
L"	var curStat = document.getElementById('lwtcursel').className;"
L"	if (curStat.indexOf('9') >= 0)"
L"	{"
L"		inlineTop -= 2;"
L"	}"
L"	statbox.style.top = inlineTop + 'px';"
L"	var inlineBottom = inlineTop + statbox.offsetHeight;"
L"	ExtrapLink(document.getElementById('lwtextrapdict1'), document.getElementById('lwtdict1').getAttribute('src'), curTerm);"
L"	ExtrapLink(document.getElementById('lwtextrapdict2'), document.getElementById('lwtdict2').getAttribute('src'), curTerm);"
L"	ExtrapLink(document.getElementById('lwtextrapgoogletrans'), document.getElementById('lwtgoogletrans').getAttribute('src'), curTerm);"
L"/**/			statbox.style.display = 'block';"
L"	if (inlineBottom > window.pageYOffset + window.innerHeight)"
L"		statbox.scrollIntoView(false);"
L"	}"
L"}"
L""
L"function traverseDomTree_NextNodeByTagName(elem, aTagName)"
L"{"
L"	if (elem.hasChildNodes() == true)"
L"	{"
L"		if (elem.firstChild.tagName == aTagName)"
L"			return elem.firstChild;"
L"		else"
L"			return traverseDomTree_NextNodeByTagName(elem.firstChild, tagName);"
L"	}"
L""
L"	var possNextElem = elem.nextSibling;"
L"	if (possNextElem == null)"
L"	{"
L"		while (elem.parentNode.nextSibling == null)"
L"		{"
L"			elem = elem.parentNode;"
L"			if (elem == null)"
L"				return null;"
L"		}"
L""
L"		return traverseDomTree_NextNodeByTagName(elem.parentNode.nextSibling, tagName);"
L"	}"
L""
L"	if (possNextElem.tagName == aTagName)"
L"		return possNextElem;"
L"	else"
L"		return traverseDomTree_NextNodeByTagName(possNextElem, tagName);"
L"}"
L""
L"function getMWList(elem)"
L"{"
L"	var bWithSpaces = false;"
L"	if (document.getElementById('lwtwithspaces').getAttribute('value') == 'yes')"
L"		bWithSpaces = true;"
L""
L"	var mwList = new Array(8);"
L"	for (int i = 0; i < 8; i++)"
L"	{"
L"		mwList[i] = '';"
L"	}"
L""
L"	var curTerm = elem.getAttribute('lwtterm');"
L"		"
L"	if (curTerm.length <= 0)"
L"		return mwList;"
L"	"
L"	var accrueTerm = curTerm;"
L""
L"	for (int i = 0; i < 8; i++)"
L"	{"
L"		elem = traverseDomTree_NextNodeByTagName(elem, 'SPAN');"
L""
L"		if (elem == null)"
L"			return mwList;"
L""
L"		if (elem.className == 'lwtsent')"
L"			return mwList;"
L""
L"		curTerm = elem.getAttribute('lwtterm');"
L"		if (curTerm.length <= 0)"
L"			i--;"
L"		else"
L"		{"
L"			if (bWithSpaces == true)"
L"			{"
L"				accrueTerm += ' ';"
L"			}"
L""
L"			accrueTerm += curTerm;"
L"			mwList[i] = accrueTerm;"
L"		}"
L"	}"
L""
L"	return mwList;"
L"}"